version: 0.1
os: linux
files:
  - source: /
    destination: /home/ec2-user/web-app
hooks:
  ApplicationStop:
    - location: app_stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: app_start.sh
      timeout: 300
      runas: ec2-user
